export const taxRates = [
    { title: 'Zero', rate: 0, shipping: true },
    { title: 'Default - Europe / Austria', rate: 0.20, shipping: true },
    { title: 'Default - Europe / Belgium', rate: 0.21, shipping: true },
    { title: 'Default - Europe / Bulgaria', rate: 0.20, shipping: true },
    { title: 'Default - Europe / Cyprus', rate: 0.19, shipping: true },
    { title: 'Default - Europe / Czech', rate: 0.21, shipping: true },
    { title: 'Default - Europe / Germany', rate: 0.19, shipping: true },
    { title: 'Default - Europe / Denmark', rate: 0.25, shipping: true },
    { title: 'Default - Europe / Estonia', rate: 0.20, shipping: true },
    { title: 'Default - Europe / Greece', rate: 0.24, shipping: true },
    { title: 'Default - Europe / Spain', rate: 0.21, shipping: true },
    { title: 'Default - Europe / Finland', rate: 0.24, shipping: true },
    { title: 'Default - Europe / France', rate: 0.20, shipping: true },
    { title: 'Default - Europe / Great Britain', rate: 0.20, shipping: true },
    { title: 'Default - Europe / Croatia', rate: 0.25, shipping: true },
    { title: 'Default - Europe / Hungary', rate: 0.27, shipping: true },
    { title: 'Default - Europe / Ireland', rate: 0.23, shipping: true },
    { title: 'Default - Europe / Italy', rate: 0.22, shipping: true },
    { title: 'Default - Europe / Lithuania', rate: 0.21, shipping: true },
    { title: 'Default - Europe / Latvia', rate: 0.21, shipping: true },
    { title: 'Default - Europe / Luxembourg', rate: 0.17, shipping: true },
    { title: 'Default - Europe / Malta', rate: 0.18, shipping: true },
    { title: 'Default - Europe / Netherlands', rate: 0.21, shipping: true },
    { title: 'Default - Europe / Poland', rate: 0.23, shipping: true },
    { title: 'Default - Europe / Portugal', rate: 0.23, shipping: true },
    { title: 'Default - Europe / Romania', rate: 0.19, shipping: true },
    { title: 'Default - Europe / Sweden', rate: 0.25, shipping: true },
    { title: 'Default - Europe / Slovenia', rate: 0.22, shipping: true },
    { title: 'Default - Europe / Slovakia', rate: 0.20, shipping: true }
];
