export const categories = [
    {
        title: 'Woman\'s fashion',
        slugs: ['woman-clothing'],
        icon: '',
        attributes: [
            { title: 'brands', key: 'brands' },
            { title: 'color', key: 'color' },
            { title: 'size', key: 'size' },
            { title: 'material', key: 'material' },
            { title: 'style', key: 'style' },
            { title: 'patternType', key: 'patternType' },
            { title: 'decoration', key: 'decoration' },
            { title: 'sleeveLength', key: 'sleeveLength' },
            { title: 'sleeveStyle', key: 'sleeveStyle' },
            { title: 'fabricType', key: 'fabricType' },
            { title: 'dressesLength', key: 'dressesLength' },
            { title: 'silhouette', key: 'silhouette' },
            { title: 'neckline', key: 'neckline' },
        ]
    },
    {
        title: 'Men\'s fashion',
        slugs: ['men-clothing'],
        icon: '',
        attributes: [
            { title: 'brands', key: 'brands' },
            { title: 'color', key: 'color' },
            { title: 'size', key: 'size' },
            { title: 'material', key: 'material' },
            { title: 'patternType', key: 'patternType' },
            { title: 'collar', key: 'collar' },
            { title: 'sleeveLength', key: 'sleeveLength' },
            { title: 'hooded', key: 'hooded' },
            { title: 'fabricType', key: 'fabricType' },
            { title: 'thickness', key: 'thickness' },
            { title: 'closureType', key: 'closureType' },
            { title: 'clothingLength', key: 'clothingLength' },
            { title: 'type', key: 'type' },
        ]
    },
    {
        title: 'Cellphones & Telecommunication',
        slugs: ['cellphones-and-telecommunication'],
        icon: '',
        attributes: [
            { title: 'brands', key: 'brands' },
            { title: 'origin', key: 'origin' },
            { title: 'design', key: 'design' },
            { title: 'type', key: 'type' },
        ]
    },
    {
        title: 'Computer and Office',
        slugs: ['computer-and-office'],
        icon: '',
        attributes: [
            { title: 'brands', key: 'brands' },
            { title: 'origin', key: 'origin' },
        ]
    },
    {
        title: 'Consumer electronics',
        slugs: ['consumer-electronics'],
        icon: '',
        attributes: [
            { title: 'brands', key: 'brands' },
            { title: 'function', key: 'function' },
            { title: 'language', key: 'language' },
            { title: 'type', key: 'type' },
            { title: 'compatibility', key: 'compatibility' },
            { title: 'applicationAgeGroup', key: 'applicationAgeGroup' },
            { title: 'style', key: 'style' },
        ]
    },
    {
        title: 'Jewelry & Watches',
        slugs: ['jewelry-and-watches'],
        icon: '',
        attributes: [
            { title: 'brands', key: 'brands' },
            { title: 'gender', key: 'gender' },
            { title: 'style', key: 'style' },
            { title: 'metalsType', key: 'metalsType' },
            { title: 'metalColor', key: 'metalColor' },
            { title: 'material', key: 'material' },
            { title: 'shapeSlashPattern', key: 'shapeSlashPattern' },
            { title: 'ringSize', key: 'ringSize' },
            { title: 'occasion', key: 'occasion' },
            { title: 'settingType', key: 'settingType' },
            { title: 'mainStone', key: 'mainStone' },
            { title: 'ringType', key: 'ringType' },
            { title: 'color', key: 'color' },
            { title: 'feature', key: 'feature' },
            { title: 'bandColor', key: 'bandColor' },
            { title: 'bandMaterialType', key: 'bandMaterialType' },
            { title: 'caseMaterialType', key: 'caseMaterialType' },
            { title: 'caseShape', key: 'caseShape' },
            { title: 'boxesAndCasesMaterial', key: 'boxesAndCasesMaterial' },
            { title: 'dialDisplay', key: 'dialDisplay' },
        ]
    },
    {
        title: 'Home, Pet & Appliances',
        slugs: ['home-per-and-appliance'],
        icon: '',
        attributes: [
            { title: 'brands', key: 'brands' },
            { title: 'color', key: 'color' },
            { title: 'size', key: 'size' },
            { title: 'occasion', key: 'occasion' },
            { title: 'material', key: 'material' },
            { title: 'pattern', key: 'pattern' },
            { title: 'season', key: 'season' },
            { title: 'certification', key: 'certification' },
            { title: 'function', key: 'function' },
            { title: 'voltage', key: 'voltage' },
            { title: 'type', key: 'type' },
            { title: 'power', key: 'power' },
            { title: 'installation', key: 'installation' },
            { title: 'capacity', key: 'capacity' },
            { title: 'timingFunction', key: 'timingFunction' },
            { title: 'waterShortagePowerOfProtection', key: 'waterShortagePowerOfProtection' },
            { title: 'humidificationMethod', key: 'humidificationMethod' },
            { title: 'noise', key: 'noise' },
            { title: 'powerType', key: 'powerType' },
            { title: 'shape', key: 'shape' },
            { title: 'application', key: 'application' },
            { title: 'use', key: 'use' },
            { title: 'operationMethod', key: 'operationMethod' },
            { title: 'humidityControl', key: 'humidityControl' },
        ]
    },
    {
        title: 'Bags & Shoes',
        slugs: ['bags-and-shoes'],
        icon: '',
        attributes: [
            { title: 'brands', key: 'brands' },
            { title: 'color', key: 'color' },
            { title: 'mainMaterial', key: 'mainMaterial' },
            { title: 'patternType', key: 'patternType' },
            { title: 'style', key: 'style' },
            { title: 'closureType', key: 'closureType' },
            { title: 'decoration', key: 'decoration' },
            { title: 'shape', key: 'shape' },
            { title: 'occasion', key: 'occasion' },
            { title: 'size', key: 'size' },
            { title: 'bootType', key: 'bootType' },
            { title: 'heelHeight', key: 'heelHeight' },
            { title: 'heelType', key: 'heelType' },
            { title: 'shoeSize', key: 'shoeSize' },
            { title: 'upperMaterial', key: 'upperMaterial' },
            { title: 'insoleMaterial', key: 'insoleMaterial' },
            { title: 'liningMaterial', key: 'liningMaterial' },
            { title: 'outsoleMaterial', key: 'outsoleMaterial' },
            { title: 'closureType', key: 'closureType' },
            { title: 'season', key: 'season' },
            { title: 'shaftMaterial', key: 'shaftMaterial' },
        ]
    },
    {
        title: 'Toys, Kids & Babies',
        slugs: ['toys-kids-babies'],
        icon: '',
        attributes: [
            { title: 'brands', key: 'brands' },
            { title: 'color', key: 'color' },
            { title: 'ageRange', key: 'ageRange' },
            { title: 'material', key: 'material' },
            { title: 'gender', key: 'gender' },
            { title: 'teen', key: 'teen' },
            { title: 'itemType', key: 'itemType' },
            { title: 'mfgSeriesNumber', key: 'mfgSeriesNumber' },
            { title: 'soldierAccessories', key: 'soldierAccessories' },
            { title: 'size', key: 'size' },
            { title: 'scale', key: 'scale' },
            { title: 'remoteControl', key: 'remoteControl' },
            { title: 'condition', key: 'condition' },
            { title: 'completionDegree', key: 'completionDegree' },
            { title: 'commodityAttribute', key: 'commodityAttribute' },
            { title: 'puppetsType', key: 'puppetsType' },
            { title: 'byAnimationSource', key: 'byAnimationSource' },
            { title: 'versionType', key: 'versionType' },
            { title: 'animals', key: 'animals' },
            { title: 'kidSize', key: 'kidSize' },
            { title: 'patternType', key: 'patternType' },
            { title: 'sleeveLength', key: 'sleeveLength' },
            { title: 'fabricType', key: 'fabricType' },
            { title: 'declaration', key: 'declaration' },
            { title: 'dressesLength', key: 'dressesLength' },
            { title: 'silhouette', key: 'silhouette' },
        ]
    },
    {
        title: 'Sport & Outdoor fun',
        slugs: ['sport-outdoor-fun'],
        icon: '',
        attributes: [
            { title: 'brands', key: 'brands' },
        ]
    },
    {
        title: 'Beauty, Health & Hair',
        slugs: ['beauty-health-and-hair'],
        icon: '',
        attributes: [
            { title: 'brands', key: 'brands' },
            { title: 'length', key: 'length' },
            { title: 'manufacturingProcess', key: 'manufacturingProcess' },
            { title: 'falseEyelashLength', key: 'falseEyelashLength' },
            { title: 'falseEyelashType', key: 'falseEyelashType' },
            { title: 'falseEyelashBrand', key: 'falseEyelashBrand' },
            { title: 'thickness', key: 'thickness' },
            { title: 'color', key: 'color' },
            { title: 'humanHairType', key: 'humanHairType' },
            { title: 'baseMaterial', key: 'baseMaterial' },
            { title: 'wigsLength', key: 'wigsLength' },
            { title: 'laceWigType', key: 'laceWigType' },
            { title: 'colorOfLace', key: 'colorOfLace' },
        ]
    },
    {
        title: 'Automobiles & Motorcycles',
        slugs: ['automobiles-and-motorcycles'],
        icon: '',
        attributes: [
            { title: 'brands', key: 'brands' },
            { title: 'color', key: 'color' },
            { title: 'osdLanguage', key: 'osdLanguage' },
        ]
    },
    {
        title: 'Home improvement & Tools',
        slugs: ['home-improvement-and-tools'],
        icon: '',
        attributes: [
            { title: 'brands', key: 'brands' },
            { title: 'color', key: 'color' },
            { title: 'certification', key: 'certification' },
            { title: 'voltage', key: 'voltage' },
            { title: 'diySupplies', key: 'diySupplies' },
            { title: 'type', key: 'type' },
            { title: 'bladeMaterial', key: 'bladeMaterial' },
            { title: 'handleMaterial', key: 'handleMaterial' },
        ]
    }
];
